// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pb/gate/sc_logic.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 11
type InitMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info         *MapInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	CurrentNodes []*Node  `protobuf:"bytes,2,rep,name=currentNodes,proto3" json:"currentNodes,omitempty"`
}

func (x *InitMapInfo) Reset() {
	*x = InitMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gate_sc_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMapInfo) ProtoMessage() {}

func (x *InitMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gate_sc_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMapInfo.ProtoReflect.Descriptor instead.
func (*InitMapInfo) Descriptor() ([]byte, []int) {
	return file_pb_gate_sc_logic_proto_rawDescGZIP(), []int{0}
}

func (x *InitMapInfo) GetInfo() *MapInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *InitMapInfo) GetCurrentNodes() []*Node {
	if x != nil {
		return x.CurrentNodes
	}
	return nil
}

// 12
type UpdateNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *UpdateNodes) Reset() {
	*x = UpdateNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gate_sc_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodes) ProtoMessage() {}

func (x *UpdateNodes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gate_sc_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodes.ProtoReflect.Descriptor instead.
func (*UpdateNodes) Descriptor() ([]byte, []int) {
	return file_pb_gate_sc_logic_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNodes) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_pb_gate_sc_logic_proto protoreflect.FileDescriptor

var file_pb_gate_sc_logic_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x63, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x22, 0x36, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x27, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_gate_sc_logic_proto_rawDescOnce sync.Once
	file_pb_gate_sc_logic_proto_rawDescData = file_pb_gate_sc_logic_proto_rawDesc
)

func file_pb_gate_sc_logic_proto_rawDescGZIP() []byte {
	file_pb_gate_sc_logic_proto_rawDescOnce.Do(func() {
		file_pb_gate_sc_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_gate_sc_logic_proto_rawDescData)
	})
	return file_pb_gate_sc_logic_proto_rawDescData
}

var file_pb_gate_sc_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_gate_sc_logic_proto_goTypes = []interface{}{
	(*InitMapInfo)(nil), // 0: gate_server.InitMapInfo
	(*UpdateNodes)(nil), // 1: gate_server.UpdateNodes
	(*MapInfo)(nil),     // 2: gate_server.MapInfo
	(*Node)(nil),        // 3: gate_server.Node
}
var file_pb_gate_sc_logic_proto_depIdxs = []int32{
	2, // 0: gate_server.InitMapInfo.info:type_name -> gate_server.MapInfo
	3, // 1: gate_server.InitMapInfo.currentNodes:type_name -> gate_server.Node
	3, // 2: gate_server.UpdateNodes.nodes:type_name -> gate_server.Node
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_gate_sc_logic_proto_init() }
func file_pb_gate_sc_logic_proto_init() {
	if File_pb_gate_sc_logic_proto != nil {
		return
	}
	file_pb_gate_global_define_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_gate_sc_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gate_sc_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_gate_sc_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_gate_sc_logic_proto_goTypes,
		DependencyIndexes: file_pb_gate_sc_logic_proto_depIdxs,
		MessageInfos:      file_pb_gate_sc_logic_proto_msgTypes,
	}.Build()
	File_pb_gate_sc_logic_proto = out.File
	file_pb_gate_sc_logic_proto_rawDesc = nil
	file_pb_gate_sc_logic_proto_goTypes = nil
	file_pb_gate_sc_logic_proto_depIdxs = nil
}
